name: Shravan Dinakaran
email: 
description: >- # this means to ignore newlines until "baseurl:"
  I blog to learn certain principles from areas exhaustively; then try to digest that knowledge into a form that is accessible to people who don't have time for such an extensive study.
baseurl: "" # the subpath of your site, e.g. /blog
url: 
github_username:  

# Build settings
theme: minima
plugins:
  - jekyll-feed

avatar: https://c.tenor.com/PA19Bh1MyOoAAAAM/enel.gif
footer-links:
  github: Sketchy-notabot/sketchy-notabot.github.io
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
